# http
port: 8001

# etcd
etcd:
  endpoints:
    - "127.0.0.1:2379"
  userName:
  password:
  dialTimeout: 5

mysql:
  dsn: root:123456@tcp(localhost:3306)/pink

log:
  fileName: pink.log
  level: 1
  serviceName: pink
